### ISSUE TITLE
add support for signing appx files

### ISSUE THREAD

**Issue by lnussel** [openSUSE/obs-sign#21]
For WSL we build the launcher code using mingw cross compilers for Windows. In order to be able to side-load the resulting appx file on Windows it needs to be signed. An appx file is actually just a zip file and the signature is a special file inside the zip:

https://github.com/facebook/fb-util-for-appx/blob/master/Sources/APPX.cpp#L47
https://github.com/facebook/fb-util-for-appx/blob/master/Sources/Sign.cpp

**Comment by lnussel** [comment]
package with appx is in https://build.opensuse.org/package/show/Virtualization:WSL/wsl-appx

**Comment by mlschroe** [comment]
Do you have a signer appx file as reference?

**Comment by mlschroe** [comment]
No need, I've created one.

**Comment by mlschroe** [comment]
Ok, enjoy. (Deployed on back-other, so Virtualization:WSL already uses it.)

Note that it doesn't sign appx files in rpms, thus you need to use a followup spec if you really want to have the signed appx in the ws-appx rpm.

**Comment by lkocman** [comment]
Wow this was way faster than I expected

**Comment by lnussel** [comment]
awesome! will try out

**Comment by lnussel** [comment]
unfortunately the signed appx doesn't load it Windows. It throws an error that it can't parse the appx.

**Comment by lnussel** [comment]
not sure how to debug but looking at the certificate used for the beta builds before there are slight differences. I assume sha1WithRSA vs sha256WithRSAEncryption doesn't matter. But this one is suspicious in the working cert:

>        X509v3 extensions:
>            X509v3 Basic Constraints: critical
>                CA:FALSE, pathlen:0
>            X509v3 Extended Key Usage: 
>                Code Signing, 1.3.6.1.4.1.311.10.3.13
>            2.5.29.1: 
>                07......4...g

**Comment by mlschroe** [comment]
1.3.6.1.4.1.311.10.3.13 is XCN_OID_KP_LIFETIME_SIGNING:

Limits the validity period of a signature to the validity period of the certificate. This restriction is typically used with the XCN_OID_PKIX_KP_CODE_SIGNING OID value to indicate that new time stamp semantics should be used.

2.5.29.1 is an obsolete form of the authority key identifier

Wouldn't the error be different if there was a problem with the cert?

Microsoft's SignTool can also verify the sig, maybe it gives a better error message? (It has a `/debug` option)

**Comment by mlschroe** [comment]
(Also note that windows can't load it anyway as it doesn't know the certificate. But it shouldn't give a parse error, that's a bit worrying.)

**Comment by lnussel** [comment]
I don't have that

**Comment by mlschroe** [comment]
Then get it!

**Comment by lnussel** [comment]
It's only a limited VM, from what I understand I'd need a full blows Visual Studio or SDK for it. Not really applicable. Googling around the clue was in the event log though. Microsoft->Windows->AppxPackagingOM logs errors about mismatch of the CN of the AppxManifest.xml with the one from the Certificate. Pretty tricky one.

**Comment by lnussel** [comment]
ok, now it works! And fails due to self signed but that is another story
