### ISSUE TITLE
Support resign rpm files

### ISSUE THREAD

**Issue by TommyLike** [openSUSE/obs-sign#39]
Currently when signing a signed rpm file the command will have the output as below:
```
localhost:~ # sign CUnit-2.1.3-21.oe1.aarch64.rpm
CUnit-2.1.3-21.oe1.aarch64.rpm: already signed
``
Can we support resign a rpm file such as `rpm --addsign` command ?

**Comment by adrianschroeter** [comment]
why not just calling 

 rpm --delsign $file

before?

**Comment by TommyLike** [comment]
> why not just calling
> 
> rpm --delsign $file
> 
> before?

It could be a solution when resign rpm file not considered in obs sign:)
