### ISSUE TITLE
Plan to support more types of binary?

### ISSUE THREAD

**Issue by TommyLike** [openSUSE/obs-sign#42]
Will obs-sign team support signing more types of binary? For example, the ko and EFI files.

**Comment by xsuchy** [comment]
No one requested it so far. If you state your use case... and if you submit PR then it may happen.

**Comment by TommyLike** [comment]
@xsuchy thanks, that's our use case, we need build a more generic sign server which would support more signing backends and different binaries, I am not sure if I could write perl correctly :).

**Comment by mlschroe** [comment]
I added support for PE file signing.

**Comment by mlschroe** [comment]
all done now.
